name: Deploy to AWS

on:
  push:
    tags:
      - 'v*'

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    environment: 'production'

    steps:
    - name: Notify Discord (Build Started)
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username": "AWS Bot", "content": "🚀 **Deploy iniciado na AWS!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nTag: `${{ github.ref_name }}`"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
         node-version: '18.x'

    - name: Install dependencies
      run: npm install --force
  
    - name: Build Angular App
      run: npm run build
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to S3
      run: |
        aws s3 sync ./dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
        aws s3 website s3://${{ secrets.AWS_S3_BUCKET_NAME }} --index-document index.html --error-document index.html

    - name: Notify Discord (Success)
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username": "AWS Bot", "content": "✅ **Deploy concluído com sucesso na AWS!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nTag: `${{ github.ref_name }}`"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord (Failure)
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username": "AWS Bot", "content": "❌ **Deploy falhou na AWS!**\nRepositório: `${{ github.repository }}`\nAmbiente: Produção\nTag: `${{ github.ref_name }}`"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}